name: 3D Contribution Calendar

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: |
            {
              "githubUserName": "${{ github.repository_owner }}",
              "startWeekday": 0,
              "themeName": "night-rainbow",
              "backgroundColor1": "#0a0a0f",
              "backgroundColor2": "#0a0a0f"
            }

      - uses: EndBug/add-and-commit@v9
        with:
          add: "profile-3d-contrib"
          message: "Update 3D contribution calendar [skip ci]"
